CREATE TABLE authors (
    id INT NOT NULL AUTO_INCREMENT,
    name VARCHAR(25) NOT NULL UNIQUE ,

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ,

    PRIMARY KEY (id)
);